import Link from "next/link";
import { and, asc, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { AlertTriangle, ArrowLeft, CheckCircle2, ReceiptText } from "lucide-react";
import { requireSession } from "@/auth/session";
import { AppShell } from "@/components/app-shell";
import { UtilityDocumentUploader } from "@/components/utility-document-uploader";
import { Badge, PageHeader } from "@/components/ui";
import { getDb } from "@/db/client";
import { documents, properties, renters, tenancies, units, utilityCostItems, utilityPeriods } from "@/db/schema";
import { allocateCents } from "@/domain/utility-allocation";
import { addUtilityCost, updateUtilityPeriodStatus } from "../actions";
const money = new Intl.NumberFormat("de-DE", { style: "currency", currency: "EUR" });
const days = (from: Date, to: Date) => Math.max(0, Math.ceil((to.getTime() - from.getTime()) / 86400000) + 1);
export default async function UtilityPeriodPage({ params }: { params: Promise<{ periodId: string }> }) {
  const session = await requireSession(); const { periodId } = await params; const db = getDb();
  const [period] = await db.select({ period: utilityPeriods, property: properties }).from(utilityPeriods).innerJoin(properties, eq(properties.id, utilityPeriods.propertyId)).where(and(eq(utilityPeriods.id, periodId), eq(utilityPeriods.organizationId, session.organizationId))).limit(1);
  if (!period) notFound();
  const [costs, propertyUnits, tenancyRows, receipts] = await Promise.all([
    db.select().from(utilityCostItems).where(and(eq(utilityCostItems.periodId, periodId), eq(utilityCostItems.organizationId, session.organizationId))).orderBy(asc(utilityCostItems.createdAt)),
    db.select().from(units).where(and(eq(units.propertyId, period.period.propertyId), eq(units.organizationId, session.organizationId))).orderBy(asc(units.label)),
    db.select({ tenancy: tenancies, renter: renters }).from(tenancies).innerJoin(renters, eq(renters.id, tenancies.renterId)).innerJoin(units, eq(units.id, tenancies.unitId)).where(and(eq(tenancies.organizationId, session.organizationId), eq(units.propertyId, period.period.propertyId))),
    db.select().from(documents).where(and(eq(documents.organizationId, session.organizationId), eq(documents.utilityPeriodId, periodId))).orderBy(asc(documents.createdAt)),
  ]);
  const recoverable = costs.filter((item) => item.isRecoverable); const total = recoverable.reduce((sum, item) => sum + item.amountCents, 0); const periodDays = days(period.period.startsAt, period.period.endsAt);
  const unitCostById = new Map(propertyUnits.map((unit) => [unit.id, 0]));
  for (const item of recoverable.filter((entry) => ["area", "units"].includes(entry.allocationKey))) {
    const weights = propertyUnits.map((unit) => item.allocationKey === "area" ? unit.areaSqm || 0 : 1);
    allocateCents(item.amountCents, weights).forEach((amount, index) => unitCostById.set(propertyUnits[index].id, (unitCostById.get(propertyUnits[index].id) || 0) + amount));
  }
  const allocations = propertyUnits.map((unit) => {
    const unitCosts = unitCostById.get(unit.id) || 0;
    const occupants = tenancyRows.filter((row) => row.tenancy.unitId === unit.id).map((row) => { const start = row.tenancy.startsAt > period.period.startsAt ? row.tenancy.startsAt : period.period.startsAt; const tenancyEnd = row.tenancy.endsAt ?? period.period.endsAt; const end = tenancyEnd < period.period.endsAt ? tenancyEnd : period.period.endsAt; const occupiedDays = start <= end ? days(start, end) : 0; const share = Math.round(unitCosts * occupiedDays / periodDays); const months = occupiedDays / (365.25 / 12); const advances = Math.round(row.tenancy.utilityAdvanceCents * months); return { name: `${row.renter.firstName} ${row.renter.lastName}`, occupiedDays, costs: share, advances, balance: share - advances }; });
    return { unit, unitCosts, occupants, vacancy: unitCosts - occupants.reduce((sum, item) => sum + item.costs, 0) };
  });
  const unresolvedKeys = costs.filter((item) => ["consumption", "manual"].includes(item.allocationKey));
  return <AppShell active="/app/utilities"><Link className="dossier-breadcrumb" href="/app/utilities"><ArrowLeft size={14} /> Betriebskosten</Link><PageHeader eyebrow={`${period.property.name} · ${period.period.status === "final" ? "Abgeschlossen" : "In Bearbeitung"}`} title={period.period.title} description={`${period.period.startsAt.toLocaleDateString("de-DE")} – ${period.period.endsAt.toLocaleDateString("de-DE")}`} action={<Badge tone={period.period.status === "final" ? "success" : "warning"}>{period.period.status === "final" ? "Abgeschlossen" : period.period.status === "review" ? "Prüfung" : "Entwurf"}</Badge>} />
    <section className="kpi-grid"><article><ReceiptText size={19} /><span>Umlagefähige Kosten</span><strong>{money.format(total / 100)}</strong><small>{recoverable.length} Positionen</small></article><article><CheckCircle2 size={19} /><span>Belege</span><strong>{receipts.length}</strong><small>{receipts.filter((item) => item.extractedData).length} ausgelesen</small></article><article><AlertTriangle size={19} /><span>Offene Zuordnung</span><strong>{unresolvedKeys.length}</strong><small>Verbrauch / manuell</small></article></section>
    <div className="dashboard-grid"><form action={addUtilityCost} className="form-sheet compact-form"><input type="hidden" name="periodId" value={periodId} /><div className="form-section-heading"><span>01</span><div><h2>Kosten erfassen</h2><p>Nur laufende, vertraglich umlagefähige Kosten markieren.</p></div></div><div className="form-grid"><label className="field wide"><span>Kostenart</span><input name="label" required placeholder="z. B. Grundsteuer" /></label><label className="field"><span>Betrag €</span><input type="number" step="0.01" min="0.01" name="amount" required /></label><label className="field"><span>Umlageschlüssel</span><select name="allocationKey"><option value="area">Wohnfläche</option><option value="units">Einheiten</option><option value="consumption">Verbrauch</option><option value="manual">Manuell</option></select></label><label className="field"><span>Lieferant</span><input name="vendor" /></label><label className="field"><span>Rechnungsdatum</span><input type="date" name="invoiceDate" /></label><label className="field wide"><span>Notiz</span><input name="notes" /></label></div><input type="hidden" name="isRecoverable" value="false" /><label className="feature-check"><input type="checkbox" name="isRecoverable" value="true" defaultChecked /><span><i />Auf Mieter umlagefähig</span></label><div className="form-actions"><button className="btn">Position speichern</button></div></form><UtilityDocumentUploader organizationId={session.organizationId} userId={session.userId} periodId={periodId} /></div>
    {receipts.length > 0 && <section className="detail-panel"><div className="panel-title"><h2>Belege & Erkennungsvorschläge</h2></div><div className="detail-list">{receipts.map((receipt) => { const data = receipt.extractedData as { totalGross?: number; supplier?: string; invoiceDate?: string; status?: string } | null; return <div key={receipt.id}><dt>{receipt.title}<small>{receipt.originalFilename}</small></dt><dd>{data?.totalGross ? money.format(data.totalGross) : "manuell prüfen"}{data?.supplier ? ` · ${data.supplier}` : ""}</dd></div>; })}</div></section>}
    <section className="detail-panel"><div className="panel-title"><h2>Kostenjournal</h2></div><div className="detail-list">{costs.map((item) => <div key={item.id}><dt>{item.label}<small>{item.vendor || "ohne Lieferant"} · {item.allocationKey} · {item.isRecoverable ? "umlagefähig" : "Vermieteranteil"}</small></dt><dd>{money.format(item.amountCents / 100)}</dd></div>)}</div></section>
    <section className="detail-panel"><div className="panel-title"><h2>Vorläufige Abrechnung je Einheit</h2></div>{unresolvedKeys.length > 0 && <div className="warning-ledger"><p>Positionen nach Verbrauch oder manueller Zuordnung sind noch nicht in der Vorschau enthalten.</p></div>}<div className="candidate-table-wrap"><table className="candidate-table"><thead><tr><th>Einheit / Mietpartei</th><th>Tage</th><th>Kostenanteil</th><th>Vorauszahlung</th><th>Saldo</th></tr></thead><tbody>{allocations.flatMap((allocation) => allocation.occupants.length ? allocation.occupants.map((occupant) => <tr key={`${allocation.unit.id}-${occupant.name}`}><td><strong>{allocation.unit.label}</strong><br />{occupant.name}</td><td>{occupant.occupiedDays}</td><td>{money.format(occupant.costs / 100)}</td><td>{money.format(occupant.advances / 100)}</td><td>{money.format(occupant.balance / 100)}</td></tr>) : [<tr key={allocation.unit.id}><td><strong>{allocation.unit.label}</strong><br />Leerstand</td><td>{periodDays}</td><td>{money.format(allocation.vacancy / 100)}</td><td>–</td><td>Vermieter</td></tr>])}</tbody></table></div></section>
    <section className="approval-panel"><CheckCircle2 size={22} /><div><h2>Abrechnung abschließen</h2><p>Vor Abschluss müssen Verbrauchswerte, Mieterwechsel, Vorauszahlungen, CO₂-Aufteilung und Heizkostenabrechnung geprüft sein.</p></div><form action={updateUtilityPeriodStatus}><input type="hidden" name="id" value={periodId} /><button className="btn secondary" name="status" value="review">Zur Prüfung</button><button className="btn" name="status" value="final" disabled={unresolvedKeys.length > 0}>Abschließen</button></form></section>
  </AppShell>;
}
