import Link from "next/link";
import { and, asc, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { ArrowLeft, CalendarClock, CheckCircle2, RotateCcw } from "lucide-react";
import { requireSession } from "@/auth/session";
import { AppShell } from "@/components/app-shell";
import { Badge, PageHeader } from "@/components/ui";
import { getDb } from "@/db/client";
import { contacts, maintenanceCases, maintenanceEvents, properties, units } from "@/db/schema";
import { updateMaintenanceCase } from "../actions";
const money = new Intl.NumberFormat("de-DE", { style: "currency", currency: "EUR" });
export default async function MaintenanceDetailPage({ params }: { params: Promise<{ caseId: string }> }) {
  const session = await requireSession(); const { caseId } = await params; const db = getDb();
  const [item] = await db.select({ item: maintenanceCases, property: properties, unit: units, contact: contacts }).from(maintenanceCases).leftJoin(properties, eq(properties.id, maintenanceCases.propertyId)).leftJoin(units, eq(units.id, maintenanceCases.unitId)).leftJoin(contacts, eq(contacts.id, maintenanceCases.assigneeContactId)).where(and(eq(maintenanceCases.id, caseId), eq(maintenanceCases.organizationId, session.organizationId))).limit(1); if (!item) notFound();
  const events = await db.select().from(maintenanceEvents).where(and(eq(maintenanceEvents.caseId, caseId), eq(maintenanceEvents.organizationId, session.organizationId))).orderBy(asc(maintenanceEvents.createdAt));
  return <AppShell active="/app/maintenance"><Link className="dossier-breadcrumb" href="/app/maintenance"><ArrowLeft size={14}/> Wartungen & Fälle</Link><PageHeader eyebrow={`${item.item.category} · ${item.property?.name || "Allgemein"}${item.unit ? ` · ${item.unit.label}` : ""}`} title={item.item.title} description={item.item.description || ""} action={<Badge tone={item.item.status === "resolved" ? "success" : item.item.priority === "urgent" ? "urgent" : "warning"}>{item.item.status === "resolved" ? "Erledigt" : item.item.status === "scheduled" ? "Terminiert" : "Offen"}</Badge>} />
    <section className="source-metadata"><div><span>Zuständig</span><strong>{item.contact?.company || item.contact?.name || "Offen"}</strong></div><div><span>Fällig</span><strong>{item.item.dueAt?.toLocaleDateString("de-DE") || "–"}</strong></div><div><span>Termin</span><strong>{item.item.scheduledAt?.toLocaleDateString("de-DE") || "–"}</strong></div><div><span>Kosten</span><strong>{item.item.actualCostCents != null ? money.format(item.item.actualCostCents / 100) : item.item.estimatedCostCents != null ? `~ ${money.format(item.item.estimatedCostCents / 100)}` : "–"}</strong></div></section>
    <div className="dashboard-grid"><section className="detail-panel"><div className="panel-title"><h2>Verlauf</h2></div><ol className="ledger-list">{events.map((event) => <li className="ledger-item" key={event.id}><time className="ledger-time">{event.createdAt.toLocaleDateString("de-DE")}</time><div className="ledger-track"><span className="ledger-node"/></div><div className="ledger-copy"><h3>{event.type.replace("status.", "Status: ")}</h3><p>{event.note || "Status aktualisiert"}</p></div></li>)}</ol></section><form className="form-sheet compact-form" action={updateMaintenanceCase}><input type="hidden" name="id" value={caseId}/><div className="form-section-heading"><span><CalendarClock size={16}/></span><div><h2>Vorgang aktualisieren</h2></div></div><div className="form-grid"><label className="field wide"><span>Status</span><select name="status" defaultValue={item.item.status}><option value="open">Offen</option><option value="scheduled">Terminiert</option><option value="resolved">Erledigt</option></select></label><label className="field"><span>Termin</span><input type="date" name="scheduledAt" defaultValue={item.item.scheduledAt?.toISOString().slice(0,10)}/></label><label className="field"><span>Tatsächliche Kosten €</span><input type="number" step="0.01" min="0" name="actualCost" defaultValue={item.item.actualCostCents == null ? "" : item.item.actualCostCents / 100}/></label><label className="field wide"><span>Verlaufsnotiz</span><textarea name="note" rows={4}/></label></div><div className="form-actions"><button className="btn">{item.item.status === "resolved" ? <RotateCcw size={15}/> : <CheckCircle2 size={15}/>} Speichern</button></div></form></div>
  </AppShell>;
}
