import { AppShell } from "@/components/app-shell";
import { Badge, PageHeader } from "@/components/ui";
import { sources } from "@/lib/demo-data";

export default function RentIndexPage() {
  return <AppShell active="/app/rent-index">
    <PageHeader eyebrow="Quellenregister" title="Mietspiegel & Bewertungen" description="Vergleichsmieten mit Quelle, Version und Prüfstatus — damit jede Einschätzung nachvollziehbar bleibt." action={<span className="availability-note">Weitere Quellen werden über den geplanten Import-Assistenten ergänzt.</span>} />
    <div className="source-grid">{sources.map((source) => <article className="source-card" key={source.city}><div className="source-card-header"><div><span className="eyebrow">{source.city}</span><h2>{source.title}</h2><p>{source.provider}</p></div><Badge tone={source.tone}>{source.status}</Badge></div><div className="source-details"><div><span>Version</span><strong>{source.version}</strong></div><div><span>Letzte Aktualisierung</span><strong>{source.date}</strong></div><div><span>Abdeckung</span><strong>{source.coverage}</strong></div><div><span>Verwendung</span><strong>{source.tone === "success" ? "Bewertungen aktiv" : "Bis Freigabe gesperrt"}</strong></div></div></article>)}</div>
    <section className="ledger" aria-labelledby="assessment-title"><div className="section-heading"><h2 id="assessment-title">Letzte Bewertungen</h2><span>Regelbasierte Vorprüfung</span></div><div className="table-wrap"><table className="data-table responsive-table"><thead><tr><th>Einheit</th><th>Aktuelle Miete</th><th>Orientierungswert</th><th>Quelle</th><th>Status</th></tr></thead><tbody><tr><td data-label="Einheit"><strong>Kastanienhof · EG links</strong><small>82 m² · Baujahr 1984</small></td><td data-label="Aktuelle Miete" className="tabular">12,68 € / m²</td><td data-label="Orientierungswert" className="tabular">13,55 € / m²</td><td data-label="Quelle">Köln 2025 · V2025.1</td><td data-label="Status"><Badge tone="warning">Quelle prüfen</Badge></td></tr><tr><td data-label="Einheit"><strong>Rheinblick · 1. OG</strong><small>91 m² · Baujahr 1991</small></td><td data-label="Aktuelle Miete" className="tabular">12,97 € / m²</td><td data-label="Orientierungswert" className="tabular">14,02 € / m²</td><td data-label="Quelle">Bonn 2024 · V2024.2</td><td data-label="Status"><Badge tone="success">Nachvollziehbar</Badge></td></tr></tbody></table></div></section>
  </AppShell>;
}
