import Link from "next/link";
import { and, asc, desc, eq, inArray } from "drizzle-orm";
import { notFound } from "next/navigation";
import { ArrowLeft, Banknote, Building2, DoorOpen, History, Link2, ReceiptText, TrendingUp, UserRound } from "lucide-react";
import { requireSession } from "@/auth/session";
import { AppShell } from "@/components/app-shell";
import { Badge, PageHeader } from "@/components/ui";
import { PortalCommunicationSection } from "@/components/portal-communication-section";
import { getDb } from "@/db/client";
import { portalItemEntries, portalItems, properties, rentChanges, renters, shareLinks, tenancies, units } from "@/db/schema";
import { createRentChange, deleteArchivedTenancy, endTenancy, restoreArchivedTenancy, revokeShareLink, updateTenancyPaymentDetails } from "../actions";

const money = new Intl.NumberFormat("de-DE", { style: "currency", currency: "EUR" });

export default async function TenancyDetailPage({ params, searchParams }: {
  params: Promise<{ tenancyId: string }>;
  searchParams: Promise<{ deleteBlocked?: string; restoreBlocked?: string; restored?: string; ended?: string; archivedWriteBlocked?: string; paymentDetailsUpdated?: string; rentChangeCreated?: string; portal?: string }>;
}) {
  const session = await requireSession();
  const [{ tenancyId }, query] = await Promise.all([params, searchParams]);
  const db = getDb();
  const [row] = await db.select({ tenancy: tenancies, renter: renters, unit: units, property: properties })
    .from(tenancies)
    .innerJoin(renters, and(eq(renters.id, tenancies.renterId), eq(renters.organizationId, session.organizationId)))
    .innerJoin(units, and(eq(units.id, tenancies.unitId), eq(units.organizationId, session.organizationId)))
    .innerJoin(properties, and(eq(properties.id, units.propertyId), eq(properties.organizationId, session.organizationId)))
    .where(and(eq(tenancies.id, tenancyId), eq(tenancies.organizationId, session.organizationId))).limit(1);
  if (!row) notFound();
  const [changes, links, communicationItems] = await Promise.all([
    db.select().from(rentChanges).where(and(eq(rentChanges.organizationId, session.organizationId), eq(rentChanges.tenancyId, tenancyId))).orderBy(desc(rentChanges.effectiveFrom)),
    db.select().from(shareLinks).where(and(eq(shareLinks.organizationId, session.organizationId), eq(shareLinks.tenancyId, tenancyId))).orderBy(desc(shareLinks.createdAt)),
    db.select().from(portalItems).where(and(eq(portalItems.organizationId, session.organizationId), eq(portalItems.tenancyId, tenancyId))).orderBy(desc(portalItems.createdAt)),
  ]);
  const communicationEntries = communicationItems.length ? await db.select().from(portalItemEntries).where(and(eq(portalItemEntries.organizationId, session.organizationId), inArray(portalItemEntries.portalItemId, communicationItems.map((item) => item.id)))).orderBy(asc(portalItemEntries.createdAt)) : [];
  const now = new Date();
  const archived = Boolean(row.tenancy.endsAt && row.tenancy.endsAt < now);

  return <AppShell active="/app/tenancies">
    <Link className="dossier-breadcrumb" href="/app/tenancies"><ArrowLeft size={14}/> Mietverhältnisse</Link>
    {archived && <div className="info-banner archived-state-banner" role="status"><strong>Archiviertes Mietverhältnis</strong><span>Historische Angaben bleiben lesbar. Änderungen sind erst nach einer Wiederherstellung möglich.</span></div>}
    {query.ended === "1" && <div className="success-banner" role="status">Das Vertragsende wurde gespeichert und alle aktiven Mieterlinks wurden widerrufen.</div>}
    {query.paymentDetailsUpdated === "1" && <div className="success-banner" role="status">Portal- und Zahlungsangaben wurden gespeichert.</div>}
    {query.rentChangeCreated === "1" && <div className="success-banner" role="status">Mietänderung wurde gespeichert.</div>}
    {query.archivedWriteBlocked === "1" && <div className="error-banner" role="alert">Archivierte Mietverhältnisse sind schreibgeschützt. Bitte zuerst wiederherstellen.</div>}
    {query.portal && query.portal !== "readonly" && <div className="success-banner" role="status">Die Portal-Kommunikation wurde aktualisiert.</div>}
    {query.portal === "readonly" && <div className="error-banner" role="alert">Beendete Mietverhältnisse sind schreibgeschützt.</div>}
    <PageHeader eyebrow={`${row.property.name} · ${row.unit.label}`} title={`${row.renter.firstName} ${row.renter.lastName}`} description={`${row.tenancy.startsAt.toLocaleDateString("de-DE")} – ${row.tenancy.endsAt?.toLocaleDateString("de-DE") || "unbefristet"}`} action={!archived ? <div className="dossier-actions"><Link className="btn" href={`/app/payments?tenancyId=${row.tenancy.id}`}><Banknote size={15}/> Zahlung buchen</Link><Link className="btn secondary" href={`/app/utilities?propertyId=${row.property.id}&unitId=${row.unit.id}`}><ReceiptText size={15}/> Betriebskosten</Link><Link className="context-link" href={`/app/documents?tenancyId=${row.tenancy.id}#document-upload`}>Dokument hochladen</Link></div> : undefined} />
    <nav className="context-navigation" aria-label="Verknüpfte Dossiers"><Link href={`/app/renters/${row.renter.id}`}><UserRound size={15}/> {row.renter.firstName} {row.renter.lastName}</Link><Link href={`/app/units/${row.unit.id}`}><DoorOpen size={15}/> {row.unit.label}</Link><Link href={`/app/properties/${row.property.id}`}><Building2 size={15}/> {row.property.name}</Link><Badge tone={archived ? "" : "success"}>{money.format(row.tenancy.coldRentCents / 100)} kalt</Badge></nav>
    <section className="source-metadata"><div><span>Kaltmiete</span><strong>{money.format(row.tenancy.coldRentCents / 100)}</strong></div><div><span>Nebenkosten</span><strong>{money.format(row.tenancy.utilityAdvanceCents / 100)}</strong></div><div><span>Kaution</span><strong>{money.format(row.tenancy.depositCents / 100)}</strong></div><div><span>Letzte Anpassung</span><strong>{row.tenancy.lastRentIncreaseAt?.toLocaleDateString("de-DE") || "–"}</strong></div></section>
    <div className="dashboard-grid">
      <section className="detail-panel"><div className="panel-title"><History size={17}/><h2>Miethistorie</h2></div><div className="detail-list">{changes.length ? changes.map((change) => <div key={change.id}><dt>{change.effectiveFrom.toLocaleDateString("de-DE")}<small>{change.changeType} · {change.status}</small></dt><dd>{money.format(change.oldColdRentCents / 100)} → <strong>{money.format(change.newColdRentCents / 100)}</strong></dd></div>) : <p className="panel-empty">Noch keine Mietänderung erfasst.</p>}</div></section>
      {!archived && <form className="form-sheet compact-form" action={createRentChange}><input type="hidden" name="tenancyId" value={tenancyId}/><div className="form-section-heading"><span><TrendingUp size={16}/></span><div><h2>Mietänderung</h2></div></div><div className="form-grid"><label className="field"><span>Gültig ab</span><input name="effectiveFrom" type="date" required/></label><label className="field"><span>Neue Kaltmiete €</span><input name="newColdRent" type="number" step="0.01" min="0" required/></label><label className="field"><span>Art</span><select name="changeType"><option value="comparison_rent">Vergleichsmiete</option><option value="index">Indexmiete</option><option value="stepped">Staffelmiete</option><option value="modernization">Modernisierung</option><option value="agreement">Vereinbarung</option></select></label><label className="field"><span>Status</span><select name="status"><option value="draft">Entwurf</option><option value="announced">Angekündigt</option><option value="accepted">Akzeptiert</option><option value="active">Aktiv</option><option value="discarded">Verworfen</option></select></label><label className="field wide"><span>Begründung</span><textarea name="reason" rows={3}/></label></div><div className="form-actions"><button className="btn">Änderung speichern</button></div></form>}
    </div>
    <PortalCommunicationSection tenancyId={tenancyId} activeItems={communicationItems.filter((item) => !item.archivedAt)} archivedItems={communicationItems.filter((item) => item.archivedAt)} entries={communicationEntries} readOnly={archived} activeLinkCount={links.filter((link) => !link.revokedAt && link.expiresAt > now).length}/>
    <section className="detail-panel"><div className="panel-title"><Link2 size={17}/><h2>Mieterlinks</h2></div><div className="detail-list">{links.length ? links.map((link) => <div key={link.id}><dt>{link.createdAt.toLocaleString("de-DE")}<small>gültig bis {link.expiresAt.toLocaleDateString("de-DE")}{link.lastAccessedAt ? ` · letzter Zugriff ${link.lastAccessedAt.toLocaleDateString("de-DE")}` : ""}</small></dt><dd>{link.revokedAt ? "Widerrufen" : archived ? "Historischer Link" : <form action={revokeShareLink}><input type="hidden" name="id" value={link.id}/><button className="text-button">Widerrufen</button></form>}</dd></div>) : <p className="panel-empty">Noch keine Mieterlinks erstellt.</p>}</div></section>
    {query.deleteBlocked === "1" && <div className="error-banner">Dieses Mietverhältnis hat noch Zahlungen, Dokumente, Mietänderungen oder Portal-Kommunikation und kann deshalb nicht endgültig gelöscht werden.</div>}
    {query.restored === "1" && <div className="success-banner">Das Mietverhältnis wurde wiederhergestellt.</div>}
    {query.restoreBlocked === "conflict" && <div className="error-banner">Für diese Einheit besteht bereits ein aktives oder zukünftiges Mietverhältnis.</div>}
    {query.restoreBlocked === "inactive-context" && <div className="error-banner">Archivierte Objekte oder Einheiten müssen zuerst wiederhergestellt werden.</div>}
    {!archived && <section className="detail-panel"><div className="panel-title"><Banknote size={17}/><h2>Zahlung & Kaution im Mieterportal</h2></div><form action={updateTenancyPaymentDetails} className="lifecycle-form"><input type="hidden" name="id" value={row.tenancy.id}/><label className="field"><span>Mietfälligkeit (Tag)</span><input name="rentDueDay" type="number" min="1" max="28" defaultValue={row.tenancy.rentDueDay || ""} placeholder="Organisationseinstellung"/></label><label className="field"><span>Verwendungszweck</span><input name="paymentReference" defaultValue={row.tenancy.paymentReference || ""} placeholder={`${row.property.name} · ${row.unit.label}`}/></label><label className="field"><span>Kaution bezahlt €</span><input name="depositPaid" type="number" min="0" step="0.01" defaultValue={row.tenancy.depositPaidCents / 100}/></label><label className="field"><span>Bezahlt am</span><input name="depositPaidAt" type="date" defaultValue={row.tenancy.depositPaidAt?.toISOString().slice(0,10) || ""}/></label><label className="field"><span>Zurückgezahlt am</span><input name="depositReturnedAt" type="date" defaultValue={row.tenancy.depositReturnedAt?.toISOString().slice(0,10) || ""}/></label><button className="btn secondary">Portalangaben speichern</button></form></section>}
    <section className="detail-panel lifecycle-panel"><div className="panel-title"><h2>Vertragslebenszyklus</h2></div>{!archived ? <form action={endTenancy} className="lifecycle-form"><input type="hidden" name="id" value={row.tenancy.id}/><label className="field"><span>Bestätigtes Vertragsende</span><input type="date" name="endsAt" min={row.tenancy.startsAt.toISOString().slice(0,10)} defaultValue={row.tenancy.endsAt?.toISOString().slice(0,10)} required/></label><label className="field"><span>Zur Bestätigung BEENDEN eingeben</span><input name="confirmation" pattern="BEENDEN" required/></label><p className="form-help">Das Mietverhältnis wird zum gewählten Datum archiviert. Alle aktiven Mieterlinks werden sofort widerrufen.</p><button className="btn secondary">Mietverhältnis beenden und archivieren</button></form> : <div className="lifecycle-actions"><form action={restoreArchivedTenancy}><input type="hidden" name="id" value={row.tenancy.id}/><label className="field"><span>WIEDERHERSTELLEN eingeben</span><input name="confirmation" pattern="WIEDERHERSTELLEN" required/></label><button className="btn secondary">Mietverhältnis wiederherstellen</button></form><details className="danger-zone"><summary>Archivierten Vertrag endgültig löschen</summary><p>Nur referenzfreie Archivdaten können gelöscht werden. Zahlungen, Dokumente oder Mietänderungen blockieren den Vorgang.</p><form action={deleteArchivedTenancy}><input type="hidden" name="id" value={row.tenancy.id}/><label className="field"><span>ARCHIV LÖSCHEN eingeben</span><input name="confirmation" pattern="ARCHIV LÖSCHEN" required/></label><label className="feature-check"><input type="checkbox" name="irreversible" value="yes" required/><span><i/>Ich bestätige, dass dieser Vorgang unumkehrbar ist.</span></label><button className="btn secondary">Endgültig löschen</button></form></details></div>}</section>
  </AppShell>;
}
