import Link from "next/link";
import { and, desc, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { ArrowLeft, Banknote, Building2, DoorOpen, History, Link2, ReceiptText, TrendingUp, UserRound } from "lucide-react";
import { requireSession } from "@/auth/session";
import { AppShell } from "@/components/app-shell";
import { Badge, PageHeader } from "@/components/ui";
import { getDb } from "@/db/client";
import { properties, rentChanges, renters, shareLinks, tenancies, units } from "@/db/schema";
import { createRentChange, revokeShareLink } from "../actions";
const money = new Intl.NumberFormat("de-DE", { style: "currency", currency: "EUR" });
export default async function TenancyDetailPage({ params }: { params: Promise<{ tenancyId: string }> }) {
  const session = await requireSession(); const { tenancyId } = await params; const db = getDb();
  const [row] = await db.select({ tenancy: tenancies, renter: renters, unit: units, property: properties }).from(tenancies).innerJoin(renters, and(eq(renters.id, tenancies.renterId), eq(renters.organizationId, session.organizationId))).innerJoin(units, and(eq(units.id, tenancies.unitId), eq(units.organizationId, session.organizationId))).innerJoin(properties, and(eq(properties.id, units.propertyId), eq(properties.organizationId, session.organizationId))).where(and(eq(tenancies.id, tenancyId), eq(tenancies.organizationId, session.organizationId))).limit(1); if (!row) notFound();
  const [changes, links] = await Promise.all([db.select().from(rentChanges).where(and(eq(rentChanges.organizationId, session.organizationId), eq(rentChanges.tenancyId, tenancyId))).orderBy(desc(rentChanges.effectiveFrom)), db.select().from(shareLinks).where(and(eq(shareLinks.organizationId, session.organizationId), eq(shareLinks.tenancyId, tenancyId))).orderBy(desc(shareLinks.createdAt))]);
  return <AppShell active="/app/tenancies"><Link className="dossier-breadcrumb" href="/app/tenancies"><ArrowLeft size={14}/> Mietverhältnisse</Link><PageHeader eyebrow={`${row.property.name} · ${row.unit.label}`} title={`${row.renter.firstName} ${row.renter.lastName}`} description={`${row.tenancy.startsAt.toLocaleDateString("de-DE")} – ${row.tenancy.endsAt?.toLocaleDateString("de-DE") || "unbefristet"}`} action={<div className="dossier-actions"><Link className="btn" href={`/app/payments?tenancyId=${row.tenancy.id}`}><Banknote size={15}/> Zahlung buchen</Link><Link className="btn secondary" href={`/app/utilities?propertyId=${row.property.id}&unitId=${row.unit.id}`}><ReceiptText size={15}/> Betriebskosten</Link></div>} />
    <nav className="context-navigation" aria-label="Verknüpfte Dossiers"><Link href={`/app/renters/${row.renter.id}`}><UserRound size={15}/> {row.renter.firstName} {row.renter.lastName}</Link><Link href={`/app/units/${row.unit.id}`}><DoorOpen size={15}/> {row.unit.label}</Link><Link href={`/app/properties/${row.property.id}`}><Building2 size={15}/> {row.property.name}</Link><Badge tone="success">{money.format(row.tenancy.coldRentCents / 100)} kalt</Badge></nav>
    <section className="source-metadata"><div><span>Kaltmiete</span><strong>{money.format(row.tenancy.coldRentCents / 100)}</strong></div><div><span>Nebenkosten</span><strong>{money.format(row.tenancy.utilityAdvanceCents / 100)}</strong></div><div><span>Kaution</span><strong>{money.format(row.tenancy.depositCents / 100)}</strong></div><div><span>Letzte Anpassung</span><strong>{row.tenancy.lastRentIncreaseAt?.toLocaleDateString("de-DE") || "–"}</strong></div></section>
    <div className="dashboard-grid"><section className="detail-panel"><div className="panel-title"><History size={17}/><h2>Miethistorie</h2></div><div className="detail-list">{changes.length ? changes.map((change) => <div key={change.id}><dt>{change.effectiveFrom.toLocaleDateString("de-DE")}<small>{change.changeType} · {change.status}</small></dt><dd>{money.format(change.oldColdRentCents / 100)} → <strong>{money.format(change.newColdRentCents / 100)}</strong></dd></div>) : <p className="panel-empty">Noch keine Mietänderung erfasst.</p>}</div></section><form className="form-sheet compact-form" action={createRentChange}><input type="hidden" name="tenancyId" value={tenancyId}/><div className="form-section-heading"><span><TrendingUp size={16}/></span><div><h2>Mietänderung</h2></div></div><div className="form-grid"><label className="field"><span>Gültig ab</span><input name="effectiveFrom" type="date" required/></label><label className="field"><span>Neue Kaltmiete €</span><input name="newColdRent" type="number" step="0.01" min="0" required/></label><label className="field"><span>Art</span><select name="changeType"><option value="comparison_rent">Vergleichsmiete</option><option value="index">Indexmiete</option><option value="stepped">Staffelmiete</option><option value="modernization">Modernisierung</option><option value="agreement">Vereinbarung</option></select></label><label className="field"><span>Status</span><select name="status"><option value="draft">Entwurf</option><option value="announced">Angekündigt</option><option value="accepted">Akzeptiert</option><option value="active">Aktiv</option><option value="discarded">Verworfen</option></select></label><label className="field wide"><span>Begründung</span><textarea name="reason" rows={3}/></label></div><div className="form-actions"><button className="btn">Änderung speichern</button></div></form></div>
    <section className="detail-panel"><div className="panel-title"><Link2 size={17}/><h2>Mieterlinks</h2></div><div className="detail-list">{links.map((link) => <div key={link.id}><dt>{link.createdAt.toLocaleString("de-DE")}<small>gültig bis {link.expiresAt.toLocaleDateString("de-DE")}{link.lastAccessedAt ? ` · letzter Zugriff ${link.lastAccessedAt.toLocaleDateString("de-DE")}` : ""}</small></dt><dd>{link.revokedAt ? "Widerrufen" : <form action={revokeShareLink}><input type="hidden" name="id" value={link.id}/><button className="text-button">Widerrufen</button></form>}</dd></div>)}</div></section>
  </AppShell>;
}
