import Link from "next/link";
import { notFound } from "next/navigation";
import { Bath, CarFront, ChefHat, DoorOpen, Layers3, Pencil, Ruler, ThermometerSun, Wind } from "lucide-react";
import { requireSession } from "@/auth/session";
import { AppShell } from "@/components/app-shell";
import { Badge } from "@/components/ui";
import { getOrganizationUnit } from "@/repositories/portfolio";

const status = { vacant: ["Frei", "warning"], occupied: ["Vermietet", "success"], owner_occupied: ["Eigennutzung", ""], renovation: ["In Sanierung", "warning"] } as const;
const money = new Intl.NumberFormat("de-DE", { style: "currency", currency: "EUR" });
export default async function UnitDetailPage({ params, searchParams }: { params: Promise<{ unitId: string }>; searchParams: Promise<{ updated?: string }> }) {
  const session = await requireSession(); const { unitId } = await params; const query = await searchParams;
  const result = await getOrganizationUnit(session.organizationId, unitId); if (!result) notFound(); const { unit, property } = result;
  return <AppShell active="/app/properties"><div className="dossier-breadcrumb"><Link href="/app/properties">Immobilien</Link><span>/</span><Link href={`/app/properties/${property.id}`}>{property.name}</Link><span>/</span><span>{unit.label}</span></div>{query.updated === "1" && <div className="success-banner" role="status">Die Stammdaten wurden aktualisiert.</div>}<header className="unit-detail-header"><div className="unit-detail-icon"><DoorOpen size={28} /></div><div><span className="eyebrow">Wohnungs-Dossier</span><h1>{unit.label}</h1><p>{property.name} · {property.street} {property.houseNumber}, {property.city}</p></div><Badge tone={status[unit.status][1]}>{status[unit.status][0]}</Badge><Link className="btn secondary" href={`/app/units/${unit.id}/edit`}><Pencil size={14} /> Bearbeiten</Link></header><section className="unit-rent-strip"><div><span>Ziel-Kaltmiete</span><strong>{unit.targetColdRentCents != null ? money.format(unit.targetColdRentCents / 100) : "–"}</strong><small>monatlicher Planwert</small></div><div><span>Nebenkosten-Schätzung</span><strong>{unit.utilityEstimateCents != null ? money.format(unit.utilityEstimateCents / 100) : "–"}</strong><small>kein Vertragswert</small></div><div><span>Wohnfläche</span><strong>{unit.areaSqm ? `${unit.areaSqm} m²` : "–"}</strong><small>{unit.roomsTimesTen ? `${unit.roomsTimesTen / 10} Zimmer` : "Zimmer nicht erfasst"}</small></div><div><span>Lage</span><strong>{unit.floor || "–"}</strong><small>im Objekt</small></div></section><div className="unit-detail-grid"><section className="detail-panel"><div className="panel-title"><Layers3 size={17} /><h2>Ausstattung &amp; Zustand</h2></div><dl className="detail-list"><Row icon={<Wind size={16} />} label="Zustand" value={unit.condition} /><Row icon={<ThermometerSun size={16} />} label="Heizung" value={[unit.heatingType, unit.energySource].filter(Boolean).join(" · ")} /><Row icon={<Bath size={16} />} label="Bad" value={unit.bathroom} /><Row icon={<Ruler size={16} />} label="Bodenbeläge" value={unit.flooring} /><Row icon={<CarFront size={16} />} label="Stellplätze" value={String(unit.parkingSpaces || 0)} /></dl></section><section className="detail-panel"><div className="panel-title"><ChefHat size={17} /><h2>Merkmale</h2></div><div className="feature-status-grid"><Feature label="Balkon / Terrasse" enabled={unit.hasBalcony} /><Feature label="Einbauküche" enabled={unit.hasFittedKitchen} /><Feature label="Aufzug" enabled={unit.hasElevator} /><Feature label="Barrierearm" enabled={unit.isAccessible} /></div>{unit.notes && <div className="unit-notes"><span>Interne Notiz</span><p>{unit.notes}</p></div>}</section></div><div className="legal-note">Zielmiete und Ausstattung sind Stammdaten. Rechtliche Mietanpassungen werden separat geprüft und niemals automatisch freigegeben.</div></AppShell>;
}
function Row({ icon, label, value }: { icon: React.ReactNode; label: string; value?: string | null }) { return <div><dt>{icon}<span>{label}</span></dt><dd>{value || "Nicht erfasst"}</dd></div>; }
function Feature({ label, enabled }: { label: string; enabled: boolean }) { return <div className={enabled ? "enabled" : ""}><i>{enabled ? "✓" : "–"}</i><span>{label}</span></div>; }
